---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-reviewer
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: sops-hcvault-auth
  namespace: flux-system
type: Opaque
stringData:
  sops.vault-addr: "http://vault.hashicorp.svc.cluster.local:8200"
  sops.vault-auth-method: "kubernetes"
  sops.vault-auth-path: "auth/kubernetes"
  sops.vault-auth-role: "sops"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth-reviewer
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-reviewer-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: vault-auth-reviewer
type: kubernetes.io/service-account-token