apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test
  namespace: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
        - name: secret-test
          image: busybox:1.36
          command: ["/bin/sh", "-c", "while true; do env | grep MYSQL_; sleep 10; done"]
          envFrom:
            - secretRef:
                name: mysql-secret
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
