apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: podinfo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: secret/mysql
        property: user
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: secret/mysql
        property: password
