apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: app
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-secret
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: secret/data/mysql
        property: user
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: secret/data/mysql
        property: password
