apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: podinfo
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: wordpress
        namespace: podinfo
      version: "*"
  interval: 50m
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    replicaCount: 1

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: wordpress.local
          paths:
            - path: /
              pathType: Prefix
      tls: []

    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
