apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: podinfo
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: podinfo
  interval: 50m
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    replicaCount: 1

    image:
      repository: docker.io/bitnami/wordpress
      tag: latest

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: wordpress.local
      pathType: Prefix
      extraHosts: []
      tls: []

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      image:
        registry: docker.io
        repository: bitnami/redis
        tag: 7.0.6

    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
