apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: podinfo
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: "26.0.0"   # match Bitnami’s latest version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: podinfo
  interval: 50m
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    replicaCount: 1

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: wordpress.local
      pathType: Prefix

    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
