apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-namespace.yaml
  - eso-namespace.yaml
  - hashicorp-namespace.yaml
  - ingress-nginx-namespace.yaml
  - monitoring-namespace.yaml
  - podinfo-namespace.yaml