---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    toolkit.fluxcd.io/tenant: production
    app.kubernetes.io/component: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted