apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: linksphere-to-postgres
  namespace: production
spec:
  endpointSelector:
    matchLabels:
      app: postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: linksphere-backend
        - matchLabels:
            app: linksphere-backend-helm
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP