apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: in-linksphere
  namespace: production
spec:
  endpointSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - linksphere-backend
          - linksphere-backend-helm
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: postgres
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: in-postgres
  namespace: production
spec:
  endpointSelector:
    matchLabels:
      app: postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: linksphere-backend
        - matchLabels:
            app: linksphere-backend-helm
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP