apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: production
spec:
  endpointSelector: {}
  ingress: []        # deny ALL ingress
  egress:
  - toEntities:
    - all            # allow ALL egress (pods, DNS, Internet, external IPs)