apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: production
spec:
  endpointSelector: {}
  ingress: # deny all ingress traffic
  - {}
  egress: # allow egress traffic to anywhere
  - {}