apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all
  namespace: production
spec:
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - {}   # allow from all endpoints (all pods in cluster)
  egress:
  - {}     # allow egress everywhere (pods, CIDRs, DNS, Internet)