apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deny-ingress
  namespace: production
spec:
  endpointSelector: {}
  ingress: []        # deny ALL ingress
  egress:
  - toEntities:
    - all            # allow ALL egress (pods, DNS, Internet, external IPs)
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-monitoring-and-security
  namespace: production
spec:
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: monitoring
    - matchLabels:
        io.kubernetes.pod.namespace: security