---
# This policy allows ingress traffic from the 'monitoring' and 'security' namespaces to pods in the 'production' namespace
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-monitoring-and-security
  namespace: production
spec:
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: monitoring
    - matchLabels:
        io.kubernetes.pod.namespace: security
---
# This policy allows ingress traffic from the 'ingress-nginx' namespace to pods labeled 'nginx: allow-ingress' in the 'production' namespace
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-from-nginx
  namespace: production
spec:
  endpointSelector:
    matchLabels:
      nginx: allow-ingress
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: ingress-nginx