## Secrets and Vault related network policies
#
# Purpose:
#   Define explicit allow rules to let ExternalSecrets, Vault, and the Vault
#   injector communicate across namespaces while keeping other traffic constrained
#   by a default-deny posture.
#
# Behavior summary:
#   - First document: allows ingress to Vault (namespace `hashicorp`) from the
#     `external-secrets` namespace on Vault's API port (8200).
#   - Second document: allows ingress to ExternalSecrets controllers from Vault
#     pods in the `hashicorp` namespace.
#   - Third document: allows the Vault Agent Injector to call the kube-apiserver
#     and reach production pods as part of secret injection workflows.
#
# Usage and cautions:
#   - Keep port-scoping where possible (e.g., Vault's API port) to reduce blast radius.
#   - Validate that service account and network label changes are reflected here.
#   - Test these policies in staging because missing allowances can break secret
#     synchronization and injection.
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-external-secrets-to-vault
  namespace: hashicorp
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vault
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: external-secrets
    toPorts:
    - ports:
      - port: "8200"
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-vault-to-external-secrets
  namespace: external-secrets
spec:
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: vault
        io.kubernetes.pod.namespace: hashicorp
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-vault-injector-to-production
  namespace: hashicorp
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vault-agent-injector
  egress:
  - toEntities:
    - kube-apiserver   # required for admission webhook
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: production   # allow injector → production pods
