apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost-secret
  namespace: podinfo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ghost-secret
    creationPolicy: Owner
  data:
    - secretKey: ghost-password
      remoteRef:
        key: secret/ghost
        property: adminPassword
