apiVersion: apps/v1
kind: Deployment
metadata:
  name: linksphere-frontend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linksphere-frontend
  template:
    metadata:
      labels:
        app: linksphere-frontend
    spec:
      containers:
        - name: frontend
          image: registry.gitlab.com/worlddrknss/linksphere/linksphere-frontend # {"$imagepolicy": "flux-system:linksphere-frontend"}
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linksphere-backend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linksphere-backend
  template:
    metadata:
      labels:
        app: linksphere-backend
    spec:
      containers:
        - name: backend
          image: registry.gitlab.com/worlddrknss/linksphere/linksphere-backend # {"$imagepolicy": "flux-system:linksphere-backend"}
          envFrom:
            - secretRef:
                name: linksphere-backend-env
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
