stages:
  - flux

flux-bootstrap:
  image:
    name: ghcr.io/fluxcd/flux-cli:v2.3.0
    entrypoint: ["/usr/bin/env", "sh", "-c"]
  stage: flux
  before_script:
    - apk add --no-cache aws-cli
    - export EKS_CLUSTER_NAME=$(cat scripts/terraform/cluster_name)
    - aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$TF_STATE_REGION"
  script:
    - flux check --pre
    - >
      flux bootstrap gitlab \
        --owner="$CI_PROJECT_NAMESPACE" \
        --repository="$CI_PROJECT_NAME" \
        --branch=main \
        --path=flux/clusters/${EKS_CLUSTER_NAME} \
        --token-auth