stages: [maintenance]

flux-bootstrap:
  <<: *aws-login
  image: alpine:3.20
  stage: maintenance
  before_script:
    - *aws-login
    - curl -s https://fluxcd.io/install.sh | bash
    - export EKS_CLUSTER_NAME=$(cat scripts/terraform/cluster_name)
    - aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$TF_STATE_REGION"
  script:
    - flux check --pre
    - >
      flux bootstrap gitlab \
        --owner="$CI_PROJECT_NAMESPACE" \
        --repository="$CI_PROJECT_NAME" \
        --branch=main \
        --path=flux/clusters/${EKS_CLUSTER_NAME} \
        --token-auth
  rules:
    - when: manual

include:
  - local: .gitlab/workflows/.gitlab-ci.templates.yml
