---
apiVersion: v1
kind: Namespace
metadata:
  name: wikijs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: wikijs
spec:
  interval: 24h
  url: https://bjw-s.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: wikijs
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: wikijs
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: 15.5.14
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: wikijs
      interval: 12h
  values:
    auth:
      username: wikijs
      password: wikijs-pass
      database: wikijs
    primary:
      persistence:
        enabled: true
        size: 5Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wikijs
  namespace: wikijs
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: wikijs
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: requarks/wiki
              tag: "2.5.300"
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: wikijs.example.com
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        size: 5Gi
    env:
      DB_TYPE: postgres
      DB_HOST: postgres-postgresql.wikijs.svc.cluster.local
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs-pass
      DB_NAME: wikijs
