apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-crs
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/default/kube-system/cilium/manifest  # Path to CRs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # Default Flux Git repo
  targetNamespace: kube-system
  dependsOn:
    - name: cilium
      namespace: kube-system  # Matches HelmRelease