apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.18.1"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    createNamespace: true
  values:
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - "10.42.0.0/16"
      enable-lb-ipam: true
