---
apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: uptime-kuma
spec:
  interval: 24h
  url: https://bjw-s.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template      # 👈 correct chart name
      version: 2.4.0           # 👈 must match what exists
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: uptime-kuma
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: "1.23.13"
    service:
      main:
        ports:
          http:
            port: 3001
    persistence:
      data:
        enabled: false
    ingress:
      main:
        enabled: false
