---
apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: uptime-kuma
spec:
  interval: 12h
  url: https://bjw-s.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: uptime-kuma
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: "1.23.13"   # latest as of now
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: false     # set true + configure if you want Ingress
    persistence:
      data:
        enabled: false     # disable PVC for quick test (enable for prod)
