apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linksphere-backend-env
  namespace: podinfo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linksphere-backend-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/apps/linksphere
