apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: linksphere-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: linksphere-frontend
  filterTags:
    # Match build tags like build-1, build-42, build-1337
    pattern: '^build-[0-9]+$'
    extract: '$0'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: linksphere-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: linksphere-backend
  filterTags:
    # Match build tags like build-1, build-42, build-1337
    pattern: '^build-[0-9]+$'
    extract: '$0'
  policy:
    numerical:
      order: asc