apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: linksphere-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: linksphere-frontend
  policy:
    alphabetical:
      order: asc
  filterTags:
    # Match Git commit SHA tags (7–40 hex chars)
    pattern: '^[a-f0-9]{7,40}$'
    extract: '$0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: linksphere-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: linksphere-backend
  policy:
    alphabetical:
      order: asc
  filterTags:
    # Match Git commit SHA tags (7–40 hex chars)
    pattern: '^[a-f0-9]{7,40}$'
    extract: '$0'