---
apiVersion: v1
kind: Namespace
metadata:
  name: ghost
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: ghost
spec:
  interval: 12h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 30m
  chart:
    spec:
      chart: ghost
      version: 21.2.13   # check latest
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ghost
  values:
    ghostUsername: user
    ghostPassword: password123
    ghostBlogTitle: "My Ghost Blog"
    service:
      type: ClusterIP
      port: 2368
    ingress:
      enabled: false
