---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app: kustomize-controller
spec:
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
  selector:
    app: kustomize-controller
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: flux-system
  labels:
    app: helm-controller
spec:
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
  selector:
    app: helm-controller
---
apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
  labels:
    app: source-controller
spec:
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
  selector:
    app: source-controller
---
apiVersion: v1
kind: Service
metadata:
  name: image-automation-controller-metrics
  namespace: flux-system
  labels:
    app: image-automation-controller
spec:
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
  selector:
    app: image-automation-controller
---
apiVersion: v1
kind: Service
metadata:
  name: image-reflector-controller-metrics
  namespace: flux-system
  labels:
    app: image-reflector-controller
spec:
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
  selector:
    app: image-reflector-controller
---
# Optional: Notification controller
apiVersion: v1
kind: Service
metadata:
  name: notification-controller-metrics
  namespace: flux-system
  labels:
    app: notification-controller
spec:
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
  selector:
    app: notification-controller
