---
# Kustomize Controller
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: kustomize-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: kustomize-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-kustomize-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kustomize-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
# Helm Controller
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: helm-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: helm-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-helm-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
# Source Controller
apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: source-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: source-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-source-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: source-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
# Image Automation Controller
apiVersion: v1
kind: Service
metadata:
  name: image-automation-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: image-automation-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: image-automation-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-image-automation-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: image-automation-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
# Image Reflector Controller
apiVersion: v1
kind: Service
metadata:
  name: image-reflector-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: image-reflector-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: image-reflector-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-image-reflector-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: image-reflector-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-kustomize-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-helm-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: helm-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-source-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: source-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-image-automation-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: image-automation-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-image-reflector-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: image-reflector-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      interval: 30s
