apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-system
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: http-prom
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kustomize-controller
          - helm-controller
          - source-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
---