---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-system
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: http-prom
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kustomize-controller
          - helm-controller
          - source-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app: kustomize-controller
spec:
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
  selector:
    app: kustomize-controller