---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: kustomize-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: kustomize-controller
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: helm-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: helm-controller
---
apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: source-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: source-controller
---
apiVersion: v1
kind: Service
metadata:
  name: image-automation-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: image-automation-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: image-automation-controller
---
apiVersion: v1
kind: Service
metadata:
  name: image-reflector-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: image-reflector-controller
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: image-reflector-controller
