---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app: kustomize-controller
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: kustomize-controller
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: flux-system
  labels:
    app: helm-controller
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: helm-controller
---
apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
  labels:
    app: source-controller
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: source-controller
---
apiVersion: v1
kind: Service
metadata:
  name: image-automation-controller-metrics
  namespace: flux-system
  labels:
    app: image-automation-controller
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: image-automation-controller
---
apiVersion: v1
kind: Service
metadata:
  name: image-reflector-controller-metrics
  namespace: flux-system
  labels:
    app: image-reflector-controller
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: image-reflector-controller
