---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-kustomize-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-prom
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-helm-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: helm-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-prom
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-source-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: source-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-prom
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-image-automation-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: image-automation-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-prom
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-image-reflector-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: image-reflector-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-prom
      interval: 30s
---
# Optional: Notification controller
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-notification-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: notification-controller
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-prom
      interval: 30s
