apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    spec:
      serviceAccountName: kustomize-controller
      containers:
      - name: manager
        env:
        - name: VAULT_ADDR
          value: "http://vault.hashicorp.svc.cluster.local:8200"  # Adjust to your Vault address
        - name: VAULT_AUTH_METHOD
          value: "kubernetes"
        - name: VAULT_AUTH_PATH
          value: "auth/kubernetes"
        - name: VAULT_ROLE
          value: "sops"
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/vault
          readOnly: true
      volumes:
      - name: vault-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              audience: vault
              expirationSeconds: 3600
