apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kustomize-patch.yaml
  - cilium-config.yaml
  - sops-rbac.yaml
  - vault-auth-sa.yaml
  - vault-config.yaml

patchesStrategicMerge:
  - kustomize-patch.yaml
