---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "sops"
---
apiVersion: v1
kind: Secret
metadata:
  name: kustomize-controller-token
  namespace: flux-system
  annotations:
    kubernetes.io/service-account.name: kustomize-controller
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sops-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sops-secrets-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sops-secrets-reader
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
---
# kustomize-controller-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    spec:
      serviceAccountName: kustomize-controller
      containers:
      - name: manager
        env:
        - name: VAULT_ADDR
          value: "http://vault.hashicorp.svc.cluster.local:8200"  # Adjust to your Vault address
        - name: VAULT_AUTH_METHOD
          value: "kubernetes"
        - name: VAULT_AUTH_PATH
          value: "auth/kubernetes"
        - name: VAULT_ROLE
          value: "sops"
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/vault
          readOnly: true
      volumes:
      - name: vault-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              audience: vault
              expirationSeconds: 3600