# infrastructure/configs/vault-secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.hashicorp.svc.cluster.local:8200"
      path: "secret"   # kv path
      version: "v2"    # KV engine version
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "eso-role"
          serviceAccountRef:
            name: external-secrets
