apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: mysql
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:r+ufi/y5GdwnSrJa,iv:HAHT70BuUyueExdU04RPFIqwE76wOZl6uCzXRHeClUc=,tag:imWq5gzkN3EMk1puis4R2g==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:REYkAcY=,iv:pnepJtEVrMLCYJApOkgpA1CWrc9tQF9wMkP759i7fw8=,tag:fsph3hc/KqqjVeakyS+eEw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:gDi4bZU2Z8DgE9c=,iv:T5rxA+KGE7H6xsp3T0i+hEOeJnnaf4SQE4l3PfpZY4w=,tag:ujFOlDAzBkrRAingJxqgVg==,type:str]
sops:
    hc_vault:
        - vault_address: http://vault.hashicorp.svc.cluster.local:8200
          engine_path: transit
          key_name: sops
          created_at: "2025-09-17T20:18:49Z"
          enc: vault:v1:vFKI9ESUkOJrx/CgG3AXd/HzSjls7oAcZfB+KG7dfoaNiWHICvDWf/utCAQVcurxddhejBSWUgt8agtS
    lastmodified: "2025-09-17T20:18:49Z"
    mac: ENC[AES256_GCM,data:Hs8hVQ4rjWm7An05hL1j0htulpXvNEGK11GqSNMoPbiHZBQ6aTxLe8JpCuoDHm01bJ8JZdEv7ySduVOfOr+p6XJCQdCaAGFxikgReAWfROIUCRN4MEkFD3KGVbZQtufFyOesriV4wXqcR6FKAepLLDaRHrUsn0vznpxpMPkA79w=,iv:7s2xaXY7A8knn5GFAx/OFssGZaEXFegFXiCiBDBFEGU=,tag:PV3PKpVtrp5hD+MJ4u45YQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2