---
apiVersion: v1
kind: Namespace
metadata:
  name: apache
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: apache
spec:
  interval: 12h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
spec:
  interval: 30m
  chart:
    spec:
      chart: apache
      version: "*"      # always grab the latest
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: apache
  values:
    service:
      type: ClusterIP
      ports:
        http: 80
    ingress:
      enabled: false
    persistence:
      enabled: false    # keep it ephemeral
