---
apiVersion: v1
kind: Namespace
metadata:
  name: apache
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: apache
spec:
  interval: 12h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
spec:
  releaseName: apache
  interval: 30m
  chart:
    spec:
      chart: apache
      version: 11.4.29   # 👈 pin exact version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: apache   # 👈 same ns as repo
  install:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
      ports:
        http: 80
    ingress:
      enabled: false
    persistence:
      enabled: false
