apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
spec:
  releaseName: apache
  interval: 30m
  chart:
    spec:
      chart: apache
      version: "*"                 # latest available
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system     # 👈 reference the central repo
  install:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
      ports:
        http: 80
    ingress:
      enabled: false
    persistence:
      enabled: false
