apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.18.1"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    createNamespace: true
  values:
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
          - "10.42.0.0/16"
      enable-lb-ipam: true

    operator:
      replicas: 1

    hostPort:
      enabled: false

    hubble:
      enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - icmp
          - http
      relay:
        enabled: true
        hostPort: false
      ui:
        enabled: true
        hostPort: false

    # --- Performance tuning ---
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

    endpoint:
      queueSize: 1024   # default 100 → higher for rollouts

    bpf:
      mapDynamicSizeRatio: 0.0025   # scale BPF maps
